### ISSUE TITLE
Sending emojis and other unicode characters

### ISSUE THREAD

**Issue by petter-nextcom** [PSWinCom/LinkMobility.PSWin.Client#1]
Is it possible to use the SDK to send SMS messages that contain smileys?

The classic internationalization test string "Iñtërnâtiônàlizætiøn" goes through without a hitch, but every attempt I've made at sending emojis (🤡🤝😁😊🎉👍) has failed and resulted in each sign being represented by two questions marks on the receiving phone.

Is it simply not supported, or is there a trick I'm missing?

**Comment by audunhegranes** [comment]
You should be able to send emojis by setting the Sms.Type=9, and encode it according to the specifications in the wiki:

https://wiki.pswin.com/Gateway%20XML%20API.ashx#Unicode_messages_22

https://github.com/PSWinCom/LinkMobility.PSWin.Client/blob/main/PSWin.Client/Model/Sms.cs#L100

**Comment by petter-nextcom** [comment]
Thanks for the explanation!
