### ISSUE TITLE
XmlTransport endpoint is not configurable

### ISSUE THREAD

**Issue by acn-sbuad** [PSWinCom/LinkMobility.PSWin.Client#3]
We wanted to use this client in our project for integration towards the XML API. 
However, in dev and staging we will send requests to a test gateway and in production we will send requests to a private gateway. 

Would it be possible to add an alternate constructor to the GatewayClient which also accepts the endpoint as input? 

We are happy to contribute with a PR as well, so let us know how we should proceed.

**Comment by fmelink** [comment]
Sorry for the slow response, and thanks for the PR. I've merged your changes, so they will be included in version 1.3.0 that is hopefully released soon.

**Comment by fmelink** [comment]
Version 1.3.0 is now available.
